name: 手动构建 realme GT7 Pro 内核

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: '内核版本/分支 (默认: master)'
        required: true
        default: 'master'
      defconfig:
        description: '默认配置文件'
        required: true
        default: 'vendor/realme/gt7pro_defconfig'
      enable_modules:
        description: '启用内核模块'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 安装构建依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev wget bc rsync git curl

      - name: 安装AOSP Clang工具链
        run: |
          mkdir -p /opt/clang
          cd /opt/clang
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
          tar -xf clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
          export CLANG_PATH=$(pwd)/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin

      - name: 下载 realme GT7pro-Speed 内核源码
        run: |
          git clone https://github.com/realme-kernel-opensource/realme_GT7pro-Speed-AndroidV-kernel-source -b ${{ github.event.inputs.kernel_version }} linux
          cd linux
          git log -1 # 显示当前使用的提交

      - name: 应用GT7 Pro专用补丁
        working-directory: ./linux
        run: |
          # 这里应替换为实际的补丁URL
          wget https://github.com/LiKgDg/realme-gt7pro_speed/releases/download/v1.0/realme-gt7pro-patches.zip
          unzip realme-gt7pro-patches.zip
          for patch in *.patch; do
            git apply $patch
          done

      - name: 配置内核
        working-directory: ./linux
        run: |
          export PATH=/opt/clang/bin:$PATH
          make ${{ github.event.inputs.defconfig }}
          if [[ "${{ github.event.inputs.enable_modules }}" == "true" ]]; then
            echo "CONFIG_MODULES=y" >> .config
          else
            echo "CONFIG_MODULES=n" >> .config
          fi

      - name: 构建内核
        working-directory: ./linux
        env:
          CC: /opt/clang/bin/clang
          CXX: /opt/clang/bin/clang++
          ARCH: arm64
          SUBARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
        run: |
          make -j${{ github.event.inputs.cpu_count }} Image.gz-dtb modules dtbs

      - name: 收集构建产物
        run: |
          mkdir artifacts
          cp linux/arch/arm64/boot/Image.gz-dtb artifacts/
          find linux -name "*.ko" -exec cp {} artifacts/ \;
          cp -r linux/arch/arm64/boot/dts/qcom artifacts/dts
          cp linux/.config artifacts/config

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: realme-gt7pro-kernel-${{ github.event.inputs.kernel_version }}
          path: artifacts/