name: Manual Build RMX5090 Kernel (Android 15)

on:
  workflow_dispatch:  # 支持手动触发
    inputs:
      build_comment:
        description: '构建备注（如测试版/稳定版）'
        required: false
        default: 'Android 15测试构建'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 显示构建信息
        run: |
          echo "构建备注: ${{ github.event.inputs.build_comment }}"
          echo "使用仓库主分支最新代码构建"

      - name: 安装基础依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev patch \
            gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu \
            python3 python3-pip zip libelf-dev git

      - name: 拉取内核源码（主分支最新版）
        run: |
          git clone https://github.com/realme-kernel-opensource/realme_GT7pro-Speed-AndroidV-kernel-source.git kernel
          cd kernel
          git checkout master  # 使用主分支最新代码
          git submodule update --init --recursive
          cd ..

      - name: 集成SukiSU Ultra
        working-directory: ./kernel
        run: |
          curl -LSs -o setup.sh https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh
          chmod +x setup.sh
          ./setup.sh main  # 适配Android 15的main分支
          rm -f setup.sh

      - name: 内核配置（含配置预览）
        working-directory: ./kernel
        run: |
          ARCH=arm64
          make ARCH=$ARCH mrproper
          cp arch/arm64/configs/vendor/sun_perf.config .config

          # 自动添加基础配置
          echo "CONFIG_KSU=y" >> .config
          echo "CONFIG_KPROBES=y" >> .config
          echo "CONFIG_GKI=y" >> .config
          echo "CONFIG_MACH_RMX5090=y" >> .config
          echo "CONFIG_SYSTEM_SECURITY=y" >> .config
          echo "CONFIG_LTO=y" >> .config

          # 配置预览（便于手动确认）
          echo "===== 配置预览（前10行） ====="
          head -n 10 .config

          # 保存配置
          make ARCH=$ARCH savedefconfig
          cp defconfig .config

      - name: 编译内核
        working-directory: ./kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export PATH=$PATH:/usr/bin:/usr/local/bin
          make -j$(nproc) LD=ld.lld | tee build.log  # 保存编译日志
          
          # 验证编译结果
          ls -lh arch/arm64/boot/Image || { echo "编译失败：未生成内核镜像"; exit 1; }

      - name: 打包AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3 anykernel
          cp ./kernel/arch/arm64/boot/Image ./anykernel/zImage
          
          # 写入机型和版本信息
          cat > ./anykernel/properties << EOF
          kernel.string=RMX5090 Kernel (${{ github.event.inputs.build_comment }})
          do.devicecheck=1
          device.name1=RMX5090
          device.name2=GT7ProSpeed
          supported.versions=15
          kernel.version=6.6.30-android15-master-$(git -C kernel rev-parse --short HEAD)
          EOF
          
          # 打包内核
          cd anykernel
          zip -r9 ../RMX5090-kernel-${{ github.sha }}.zip * -x .git README.md

      - name: 上传产物与日志
        uses: actions/upload-artifact@v4
        with:
          name: rmx5090-android15-kernel-${{ github.run_number }}
          path: |
            RMX5090-kernel-*.zip
            kernel/build.log

      - name: 构建完成提示
        run: |
          echo "构建完成！产物已上传至Artifacts"
          echo "内核包适用于RMX5090（Android 15系统）"
