name: Build RMX5090 Kernel (Android 15)

on:
  push:
    branches: [ master ]
    paths:
      - 'arch/arm64/configs/vendor/sun_perf.config'
      - 'Makefile'
      - 'drivers/**'
      - 'kernel/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: realme-kernel-opensource/realme_GT7pro-Speed-AndroidV-kernel-source
          path: kernel
          submodules: 'recursive'
          # 若需指定特定内核版本，可添加commit参数
          # ref: 013ec21bba94  # 替换为目标commit哈希

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev patch \
            gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu \
            python3 python3-pip zip libelf-dev  # 新增libelf-dev适配Android 15

      - name: Integrate SukiSU Ultra (Android 15兼容版)
        working-directory: ./kernel
        run: |
          curl -LSs -o setup.sh https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh
          chmod +x setup.sh
          # 针对Android 15使用main分支最新适配
          ./setup.sh main
          rm -f setup.sh

      - name: Configure kernel for Android 15 & RMX5090
        working-directory: ./kernel
        run: |
          ARCH=arm64
          make ARCH=$ARCH mrproper
          # 加载官方配置并适配Android 15
          cp arch/arm64/configs/vendor/sun_perf.config .config
          
          # 核心配置：启用KernelSU及Android 15必要选项
          echo "CONFIG_KSU=y" >> .config
          echo "CONFIG_KPROBES=y" >> .config
          echo "CONFIG_GKI=y" >> .config
          echo "CONFIG_MACH_RMX5090=y" >> .config  # 机型标识
          echo "CONFIG_ANDROID15=y" >> .config     # Android 15兼容标识
          echo "CONFIG_SYSTEM_SECURITY=y" >> .config  # 适配Android 15安全机制
          
          # 补充6.6.30内核特性
          grep -q "CONFIG_ZRAM=y" .config || echo "CONFIG_ZRAM=y" >> .config
          grep -q "CONFIG_TCP_BBR=y" .config || echo "CONFIG_TCP_BBR=y" >> .config
          grep -q "CONFIG_LTO=y" .config || echo "CONFIG_LTO=y" >> .config  # 启用LTO优化
          
          # 保存配置
          make ARCH=$ARCH savedefconfig
          cp defconfig .config

      - name: Build kernel (6.6.30-android15)
        working-directory: ./kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export PATH=$PATH:/usr/bin:/usr/local/bin
          # 针对6.6.30内核优化编译参数
          make -j$(nproc) LD=ld.lld  # 使用LLD链接器适配Android 15
          # 验证镜像
          ls -lh arch/arm64/boot/Image

      - name: Prepare AnyKernel3 (Android 15版)
        run: |
          git clone https://github.com/osm0sis/AnyKernel3 anykernel
          cp ./kernel/arch/arm64/boot/Image ./anykernel/zImage
          
          # 配置Android 15及机型信息
          echo "kernel.string=RMX5090 Kernel 6.6.30 (Android 15)" > ./anykernel/properties
          echo "do.devicecheck=1" >> ./anykernel/properties
          echo "device.name1=RMX5090" >> ./anykernel/properties
          echo "device.name2=GT7ProSpeed" >> ./anykernel/properties
          echo "supported.versions=15" >> ./anykernel/properties  # 明确支持Android 15
          echo "kernel.version=6.6.30-android15-8-g013ec21bba94" >> ./anykernel/properties

      - name: Package kernel zip
        run: |
          cd anykernel
          zip -r9 ../RMX5090-6.6.30-android15-kernel.zip * -x .git README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RMX5090-android15-kernel
          path: RMX5090-6.6.30-android15-kernel.zip
